import Foundation

#if NETSCOPE_DEV
enum UIRef: String, CaseIterable, Sendable {
  case dashboard = "NETSCOPE.DASHBOARD"
  case dashboardNetworkHeader = "NETSCOPE.DASHBOARD.NETWORK_HEADER"
  case dashboardMetrics = "NETSCOPE.DASHBOARD.METRICS"
  case dashboardChanges = "NETSCOPE.DASHBOARD.CHANGES"
  case dashboardPrimaryAction = "NETSCOPE.DASHBOARD.PRIMARY_ACTION"
  case dashboardActions = "NETSCOPE.DASHBOARD.ACTIONS"
  case dashboardHealth = "NETSCOPE.DASHBOARD.HEALTH"
  case networkOverview = "NETSCOPE.NETWORK.OVERVIEW"
  case security = "NETSCOPE.SECURITY"
  case securityHardening = "NETSCOPE.SECURITY.HARDENING"
  case securitySecrets = "NETSCOPE.SECURITY.SECRETS"
  case securityPlaybooks = "NETSCOPE.SECURITY.PLAYBOOKS"
  case securityPlaybookDetail = "NETSCOPE.SECURITY.PLAYBOOK_DETAIL"
  case securityLabs = "NETSCOPE.SECURITY.LABS"
  case securityLabDetail = "NETSCOPE.SECURITY.LAB_DETAIL"
  case scanner = "NETSCOPE.SCANNER"
  case scannerDevices = "NETSCOPE.SCANNER.DEVICES"
  case scannerServices = "NETSCOPE.SCANNER.SERVICES"
  case history = "NETSCOPE.HISTORY"
  case toolbox = "NETSCOPE.TOOLBOX"
  case toolboxNmap = "NETSCOPE.TOOLBOX.NMAP"
  case toolboxNuclei = "NETSCOPE.TOOLBOX.NUCLEI"
  case toolboxReferenceIPCIDR = "NETSCOPE.TOOLBOX.REFERENCE.IP_CIDR"
  case toolboxReferencePortsServices = "NETSCOPE.TOOLBOX.REFERENCE.PORTS_SERVICES"
  case toolboxReferenceHTTPStatus = "NETSCOPE.TOOLBOX.REFERENCE.HTTP_STATUS"
  case scannerDetails = "NETSCOPE.SCANNER.DETAILS"
  case scannerDeviceDetails = "NETSCOPE.SCANNER.DEVICE_DETAILS"
  case scannerPortScanner = "NETSCOPE.SCANNER.PORTS"
  case scannerDiagnostics = "NETSCOPE.SCANNER.DIAGNOSTICS"
  case scannerBonjour = "NETSCOPE.SCANNER.BONJOUR"
  case labs = "NETSCOPE.LABS"
  case labsMission = "NETSCOPE.LABS.MISSION"
  case labsPro = "NETSCOPE.LABS.PRO"
  case labsProgramNmap = "NETSCOPE.LABS.PROGRAM.NMAP"
  case labsProgramNuclei = "NETSCOPE.LABS.PROGRAM.NUCLEI"
  case labsProgramDig = "NETSCOPE.LABS.PROGRAM.DIG"
  case labsProgramCurl = "NETSCOPE.LABS.PROGRAM.CURL"
  case ssh = "NETSCOPE.SSH"
  case sshGuide = "NETSCOPE.SSH.GUIDE"
  case about = "NETSCOPE.ABOUT"

  var label: String {
    switch self {
    case .dashboard: "Start"
    case .dashboardNetworkHeader: "Nagłówek sieci"
    case .dashboardMetrics: "Metryki"
    case .dashboardChanges: "Zmiany sieci"
    case .dashboardPrimaryAction: "Główna akcja skanu"
    case .dashboardActions: "Szybki dostęp"
    case .dashboardHealth: "Network Health"
    case .networkOverview: "Network Overview"
    case .security: "Security"
    case .securityHardening: "Hardening Center"
    case .securitySecrets: "Secrets Inspector"
    case .securityPlaybooks: "Security Playbooks"
    case .securityPlaybookDetail: "Security Playbook — szczegóły"
    case .securityLabs: "Security Labs"
    case .securityLabDetail: "Security Lab — szczegóły"
    case .scanner: "Skaner"
    case .scannerDevices: "Urządzenia"
    case .scannerServices: "Usługi"
    case .history: "Historia skanów"
    case .toolbox: "Toolbox"
    case .toolboxNmap: "Toolbox Nmap"
    case .toolboxNuclei: "Toolbox Nuclei"
    case .toolboxReferenceIPCIDR: "Toolbox IP i CIDR"
    case .toolboxReferencePortsServices: "Toolbox Porty i usługi"
    case .toolboxReferenceHTTPStatus: "Toolbox Statusy HTTP"
    case .scannerDetails: "Szczegóły skanu"
    case .scannerDeviceDetails: "Szczegóły urządzenia"
    case .scannerPortScanner: "Skaner portów"
    case .scannerDiagnostics: "Diagnostyka"
    case .scannerBonjour: "Bonjour"
    case .labs: "Laboratoria"
    case .labsMission: "Misja laboratorium"
    case .labsPro: "Northbyte Radar Pro"
    case .labsProgramNmap: "Laboratorium Nmap"
    case .labsProgramNuclei: "Laboratorium Nuclei"
    case .labsProgramDig: "Laboratorium Dig"
    case .labsProgramCurl: "Laboratorium Curl"
    case .ssh: "Skróty SSH"
    case .sshGuide: "Przewodnik SSH"
    case .about: "Informacje"
    }
  }

  var source: String {
    switch self {
    case .dashboard, .dashboardNetworkHeader, .dashboardMetrics, .dashboardChanges, .dashboardPrimaryAction, .dashboardActions, .dashboardHealth, .networkOverview, .history: "NetScope/DashboardView.swift"
    case .security: "NetScope/AppShellView.swift"
    case .securityHardening: "NetScope/AppShellView.swift"
    case .securitySecrets: "NetScope/AppShellView.swift"
    case .securityPlaybooks: "NetScope/AppShellView.swift"
    case .securityPlaybookDetail: "NetScope/AppShellView.swift"
    case .securityLabs: "NetScope/AppShellView.swift"
    case .securityLabDetail: "NetScope/AppShellView.swift"
    case .scanner: "NetScope/ScannerView.swift"
    case .scannerDevices, .scannerServices: "NetScope/AppShellView.swift"
    case .toolbox, .toolboxNmap, .toolboxNuclei, .toolboxReferenceIPCIDR, .toolboxReferencePortsServices, .toolboxReferenceHTTPStatus: "NetScope/ToolboxView.swift"
    case .scannerDetails: "NetScope/ScanDetailsView.swift"
    case .scannerDeviceDetails: "NetScope/SupportingViews.swift"
    case .scannerPortScanner, .scannerDiagnostics, .scannerBonjour: "NetScope/AppShellView.swift"
    case .labs: "NetScope/LaboratoryView.swift"
    case .labsMission: "NetScope/TerminalLessonView.swift"
    case .labsPro, .labsProgramNmap, .labsProgramNuclei, .labsProgramDig, .labsProgramCurl: "NetScope/LabProgramView.swift"
    case .ssh, .sshGuide: "NetScope/SSHShortcutLibraryView.swift"
    case .about: "NetScope/SupportingViews.swift"
    }
  }

  var symbol: String {
    switch self {
    case .dashboard: "DashboardView"
    case .dashboardNetworkHeader: "networkHeader"
    case .dashboardMetrics: "metrics"
    case .dashboardChanges: "changes"
    case .dashboardPrimaryAction: "primaryScanAction"
    case .dashboardActions: "primaryActions"
    case .dashboardHealth: "networkHealth"
    case .networkOverview: "NetworkOverviewView"
    case .security: "SecurityView"
    case .securityHardening: "HardeningCenterView"
    case .securitySecrets: "SecretsInspectorView"
    case .securityPlaybooks: "SecurityPlaybooksView"
    case .securityPlaybookDetail: "SecurityPlaybookDetailView"
    case .securityLabs: "SecurityLabsView"
    case .securityLabDetail: "SecurityLabDetailView"
    case .scanner: "ScannerView"
    case .scannerDevices: "DevicesView"
    case .scannerServices: "ServicesHubView"
    case .history: "history"
    case .toolbox: "ToolboxView"
    case .toolboxNmap, .toolboxNuclei: "ToolLearningView"
    case .toolboxReferenceIPCIDR, .toolboxReferencePortsServices, .toolboxReferenceHTTPStatus: "ReferenceListView"
    case .scannerDetails: "ScanDetailsView"
    case .scannerDeviceDetails: "DeviceDetailView"
    case .scannerPortScanner: "PortScannerView"
    case .scannerDiagnostics: "DiagnosticsView"
    case .scannerBonjour: "ServicesView"
    case .labs: "LaboratoryView"
    case .labsMission: "TerminalLessonView"
    case .labsPro: "LabProgramView.ProSheet"
    case .labsProgramNmap, .labsProgramNuclei, .labsProgramDig, .labsProgramCurl: "LabProgramView"
    case .ssh: "SSHShortcutLibraryView"
    case .sshGuide: "NmapGuideView"
    case .about: "AboutView"
    }
  }

  var clipboardText: String {
    "UIREF: \(rawValue)\nLabel: \(label)\nSource: \(source)\nSymbol: \(symbol)"
  }
}
#endif
